// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SeleniumParserML.Model
{
    public class ModelInput
    {
        [ColumnName("_id"), LoadColumn(0)]
        public float _id { get; set; }


        [ColumnName("amountOfLikes"), LoadColumn(1)]
        public float AmountOfLikes { get; set; }


        [ColumnName("loadingDate"), LoadColumn(2)]
        public string LoadingDate { get; set; }


        [ColumnName("vehicleType"), LoadColumn(3)]
        public string VehicleType { get; set; }


        [ColumnName("cargoDescription"), LoadColumn(4)]
        public string CargoDescription { get; set; }


        [ColumnName("paymentType"), LoadColumn(5)]
        public string PaymentType { get; set; }


        [ColumnName("routFrom"), LoadColumn(6)]
        public string RoutFrom { get; set; }


        [ColumnName("routTo"), LoadColumn(7)]
        public string RoutTo { get; set; }


        [ColumnName("routFromCountry"), LoadColumn(8)]
        public string RoutFromCountry { get; set; }


        [ColumnName("routToCountry"), LoadColumn(9)]
        public string RoutToCountry { get; set; }


    }
}
